/** Program Description:
	Program Name: Minimalist Screen Sleeper
    Version: 1.5
    Developer: Raymel Francisco
    Development: 	Monday, March 30, 2015 
    					4:43 PM to 7:00 PM
    					8:52 PM to 9:57 PM
    					11:15 PM to 12:01 AM
    				Tuesday, March 31, 2015
    					10:56 AM to 12:49 PM
                    Wednesday, April 1, 2015
                        6:30 PM to 7:04 PM
                        9:44 PM to 10:40 PM
                    Thursday, April 2, 2015
                        11:41 AM to 12:00 PM
                        12:39 PM to 1:00 PM
                        3:47 PM to 4:17 PM
                        9:58 PM to 10:19 PM
					
    Written in: C, Windows Resoucrce Script, Vala
    Compiler Used: GNU GCC 4.8.1
    Text editor: Sublime Text 2 (2.0.2 build 2221)

    File details:
    Name: min_screen_sleeper_source_1.5.c
    Use in the project: Main source file of the program.
**/
 #define _WIN32_WINNT 0x0500
 #include <stdio.h>
 #include <windows.h>
 #include <unistd.h>
 #include <conio.h>
 #include <time.h>
 #include <ctype.h>
 #include "configParser.h"
 
 #ifndef TITLE_BAR_TEXT
    #define TITLE_BAR_TEXT "Minimalist Screen Sleeper 1.5"
 #endif
 
 #ifndef WINDOW_SIZE
    #define WINDOW_SIZE "mode 65, 10"
 #endif

 #ifndef DEFAULT_SECONDS_VALUE
    #define DEFAULT_SECONDS_VALUE 5
 #endif

 #ifndef SETTINGS_FILENAME
    #define SETTINGS_FILENAME "settings.ini"
 #endif

 #ifndef NON_EXISTING
    #define NON_EXISTING -1
 #endif

 #ifndef IS_EXISTING
    #define IS_EXISTING F_OK 
 #endif

 #ifndef ONE_SECOND
    #define ONE_SECOND 1000
 #endif

 #ifndef TURN_OFF
    #define TURN_OFF 2
 #endif

 #ifndef TURN_ON
    #define TURN_ON -1
 #endif

 typedef enum boolean { false = 0, true = !false } bool;
 
 void setConsoleWindowAttrib 	();
 void readSettingsFile 			(long *secondsCounter, char atRuntime [], char showConsoleWindow []);
 void consoleOutput 			(long *secondsCounter, char atRuntime []);
 void turnOffMonitor 			(bool *isSuccess);
 void runtimeChecker			(bool *isSuccess);
 
 int main (int argc, char *argv []) {

 	bool isSuccess = false;
 	long secondsCounter = DEFAULT_SECONDS_VALUE;
    char afterPause;
    char atRuntime [2];
    char showConsoleWindow [3];

 	setConsoleWindowAttrib ();
 	readSettingsFile (&secondsCounter, atRuntime, showConsoleWindow);
 	consoleOutput (&secondsCounter, atRuntime);
 	turnOffMonitor (&isSuccess);
 	runtimeChecker (&isSuccess);

 	return EXIT_SUCCESS;
 } // int main ()
 
 void setConsoleWindowAttrib () {
 	SetConsoleTitle(TITLE_BAR_TEXT);
 	system(WINDOW_SIZE);
 } // void setConsoleWindowAttrib ()

 void readSettingsFile (long *secondsCounter, char atRuntime [], char showConsoleWindow []) {

 	FILE *settingsFile;

 	if (access(SETTINGS_FILENAME, IS_EXISTING) == NON_EXISTING) {

 		fputs(" Creating settings file, please wait...", stdout);
 		settingsFile = fopen(SETTINGS_FILENAME, "w");

 		char settingFileContent [256];			 
 	
	 	strcpy(settingFileContent, "# This file is auto-generated by Minimalist Screen Sleeper.");
	 	strcat(settingFileContent, "\n# EDITING THIS FILE IS NOT ADVISABLE.");
	 	strcat(settingFileContent, "\n# Sincerely,\n# The Developer");
	 	strcat(settingFileContent, "\n\n[WaitDuration]\nseconds=5");
        strcat(settingFileContent, "\n\n[AtRuntime]\npause=32");
        strcat(settingFileContent, "\nskip=115");
	 	strcat(settingFileContent, "\n\n[ShowConsoleWindow]\nshow=yes\n");

 		if (fputs(settingFileContent, settingsFile) == EOF) {

 			fputs(" ERROR: Settings' file creation is not successful!", stdout);
 			// if (getch()) {
 			// 	exit(EXIT_FAILURE);
 			// } // if (getch())
            getch();
            exit(EXIT_FAILURE);
 		} else {
 			fputs(" Settings' file was created!\n Press any key to proceed...", stdout);
 			// if (getch()) {
 			// 	fclose(settingsFile);
    //             system("cls");
 			// } // if (getch())
            getch();
            fclose(settingsFile);
            system("cls");
 		} // if (fputs(settingFileContent, settingsFile) == EOF)
 	} // if (access(SETTINGS_FILENAME, IS_EXISTING) == NON_EXISTING)

    settingsFile = fopen(SETTINGS_FILENAME, "r");

    char lineStorage [70];
    int showGUI = 1;

    while (fgets(lineStorage, sizeof(lineStorage), settingsFile) != NULL) {
        if (strcmp(lineStorage, "[ShowConsoleWindow]\n") == 0) {
            if (fgets(lineStorage, sizeof(lineStorage), settingsFile) != NULL) {
                if (strcmp(lineStorage, "show=yes\n") == 0) {
                    showGUI = 0;
                    break;
                }
            }
        }
    }

    if (showGUI) {
        fclose(settingsFile);
        HWND hWnd = GetConsoleWindow();
        ShowWindow( hWnd, SW_MINIMIZE );
        ShowWindow( hWnd, SW_HIDE );
        system("minScreenSleeper-gui.exe");
        exit(0);
    }

    *secondsCounter = parseLong (settingsFile, SETTINGS_FILENAME, "[WaitDuration]\n", 15, "seconds", 7);
    atRuntime [0] = parseLong (settingsFile, SETTINGS_FILENAME, "[AtRuntime]\n", 12, "pause", 5);
    atRuntime [1] = parseLong (settingsFile, SETTINGS_FILENAME, "[AtRuntime]\n", 12, "skip", 4);

 	fclose(settingsFile);
 } // void readSettingsFile (int *secondsCounter)

 void consoleOutput (long *secondsCounter, char atRuntime []) {

    clock_t startTime;
    clock_t checkTime;
 	int seconds = *secondsCounter;
    char mode;
    char keyHit;

 	for (seconds; seconds > -1; seconds--) {
        system("cls");
        if (seconds > 0) {
            fprintf(stdout, "\n All active monitor(s) will be turned off in %ld s.  ", seconds);
        } else {
            fputs("\n Turning off monitor(s)...                          ", stdout);
        } // if (seconds > 0)

        startTime = clock();
        checkTime = startTime + ONE_SECOND;

        while ( checkTime > clock() ) {
            if (kbhit()) {

                keyHit = getch();
                fflush(stdin);

                if (keyHit == atRuntime [0] || keyHit == toupper(atRuntime [0])) {

                    system("cls");
                    fputs("\n PAUSED                                             ", stdout);
                    fputs("\n [r] to resume\n [t] to change current time\n \n [c] to edit settings\n [e] to exit\n > ", stdout);
                    mode = getche();
                    fflush(stdin);

                } else if (keyHit == atRuntime [1] || keyHit == toupper(atRuntime [1])) {
                    return;
                }
                
                if (mode == 'r' || mode == 'R') {
                    break;
                } else if (mode == 'e' || mode == 'E') {
                    exit(EXIT_SUCCESS);
                } else if (mode == 't' || mode == 'T') {

                    system("cls");
                    fputs("\n How many seconds: > ", stdout);
                    long sec = 0;
                    scanf("%d", &sec);
                    consoleOutput(&sec, atRuntime);
                    return;

                } else if (mode == 'c' || mode == 'C') {

                    // default values
                    long waitDuration = 0;
                    char pauseKey = 32;
                    char skipKey = 115;
                    char showConsole = 'n';

                    system("cls");
                    fputs("\n Set timer wait duration: (only ints, -1 to skip) > ", stdout);
                    scanf("%d", &waitDuration);
                    fflush(stdin);

                    fputs("\n Set pause timer hotkey: (only single char, [SPACE] to skip) > ", stdout);
                    //scanf("%d", &pauseKey);
                    pauseKey = getchar();
                    fflush(stdin);

                    fputs("\n Set skip timer hotkey: (only single char, [SPACE] to skip) > ", stdout);
                    //scanf("%d", &skipKey);
                    skipKey = getchar();
                    fflush(stdin);

                    fputs("\n Set show console window (y/n only, [SPACE] to skip) > ", stdout);
                    //scanf("%c", &showConsole);
                    showConsole = getchar();
                    fflush(stdin);
                    
                    system("cls");

                    fputs(" Updating settings file, please wait...", stdout);
                    FILE* settingsFile = fopen(SETTINGS_FILENAME, "w");

                    char settingFileContent [256];
                    char strWaitDuration[13];
                    char strPauseKey[2];
                    char strSkipKey[2];   
                
                    strcpy(settingFileContent, "# This file is auto-generated by Minimalist Screen Sleeper.");
                    strcat(settingFileContent, "\n# EDITING THIS FILE IS NOT ADVISABLE.");
                    strcat(settingFileContent, "\n# Sincerely,\n# The Developer");

                    if (waitDuration <= -1) {
                        waitDuration = *secondsCounter;
                    }

                    strcat(settingFileContent, "\n\n[WaitDuration]\nseconds=");
                    sprintf(strWaitDuration, "%d", waitDuration);
                    strcat(settingFileContent, strWaitDuration);

                    if (pauseKey <= -1 || pauseKey == 32) {
                        pauseKey = atRuntime[0];
                    }

                    strcat(settingFileContent, "\n\n[AtRuntime]\npause=");
                    sprintf(strPauseKey, "%d", pauseKey);
                    strcat(settingFileContent, strPauseKey);

                    if (skipKey <= -1 || skipKey == 32) {
                        skipKey = atRuntime[1];
                    }

                    strcat(settingFileContent, "\nskip=");
                    sprintf(strSkipKey, "%d", skipKey);
                    strcat(settingFileContent, strSkipKey);

                    strcat(settingFileContent, "\n\n[ShowConsoleWindow]\nshow=");
                    if (showConsole == 'y') {
                        strcat(settingFileContent, "yes\n");
                    } else if(showConsole == 'n') {
                        strcat(settingFileContent, "no\n");
                    } else {
                        strcat(settingFileContent, "yes\n");
                    }

                    if (fputs(settingFileContent, settingsFile) == EOF) {

                        fputs(" ERROR: Settings' file update is not successful!", stdout);
                        if (getch()) {
                            exit(EXIT_FAILURE);
                        } // if (getch())
                    } else {
                        fputs(" Settings' file was updated!\n Press any key to proceed...", stdout);
                        if (getch()) {
                            fclose(settingsFile);
                            system("cls");
                        } // if (getch())
                    } // if (fputs(settingFileContent, settingsFile) == EOF)


                    settingsFile = fopen(SETTINGS_FILENAME, "r");

                    char lineStorage [70];
                    int showGUI = 1;

                    while (fgets(lineStorage, sizeof(lineStorage), settingsFile) != NULL) {
                        if (strcmp(lineStorage, "[ShowConsoleWindow]\n") == 0) {
                            if (fgets(lineStorage, sizeof(lineStorage), settingsFile) != NULL) {
                                if (strcmp(lineStorage, "show=yes\n") == 0) {
                                    showGUI = 0;
                                    break;
                                }
                            }
                        }
                    }

                    if (showGUI) {
                        fclose(settingsFile);
                        HWND hWnd = GetConsoleWindow();
                        ShowWindow( hWnd, SW_MINIMIZE );
                        ShowWindow( hWnd, SW_HIDE );
                        system("minScreenSleeper-gui.exe");
                        exit(0);
                    }

                    consoleOutput(&waitDuration, atRuntime);
                    return;

                }
                
            } // if (kbhit())
        } // while ( checkTime > GetTickCount() )

 	} // for (seconds; seconds > -1; seconds--)
 } // void consoleOutput (int *secondsCounter)

 void turnOffMonitor (bool *isSuccess) {
     if (SendMessage(HWND_BROADCAST, WM_SYSCOMMAND, SC_MONITORPOWER, (LPARAM) TURN_OFF)) {
     	*isSuccess = true;
     } else {
     	*isSuccess = false;
     } // if (SendMessage(HWND_BROADCAST, WM_SYSCOMMAND, SC_MONITORPOWER, (LPARAM) TURN_OFF))
 } // void turnOffMonitor (bool *isSuccess)

 void runtimeChecker (bool *isSuccess) {
 	if (*isSuccess == true) {
 		return;
 	} else {
		fputs(" ERROR: Cannot turn off monitor.", stdout);
		if (getch()) {
			exit(EXIT_FAILURE);
		} // if (getch())
	} // if (isSuccess == true) 
 } // void runtimeChecker (bool *isSuccess)
